### ISSUE TITLE
Colonists fall in water and freeze up

### ISSUE THREAD

**Issue by stabtokill** [AngleWyrm/Colonies#41]
![2012-12-18_21 25 12](https://f.cloud.github.com/assets/2895786/21167/e9af731c-498b-11e2-898d-d030aadfa40b.png)

they fall in the water and don't do anything .
(pic included)

ask for my details if needed.

**Comment by stabtokill** [comment]
![2012-12-18_21 52 56](https://f.cloud.github.com/assets/2895786/21193/af8e6aea-498f-11e2-82e1-707614f96d5a.png)

Well its not just water.
Kinda funny thought, most of them all look in the same direction =)

**Comment by stabtokill** [comment]
![2012-12-18_22 50 38](https://f.cloud.github.com/assets/2895786/21251/fd0c1c4c-4997-11e2-84cd-045df804b01d.png)

lol, they keep on spawning around the townHall.

And I hope this helps you fix it. :)

**Comment by AngleWyrm** [comment]
Yeah, pretty funny. If you try to puch/interact with any of them, you will probably notice they are ghosts.

I've narrowed the problem down to what I believe is happening:  #42 Chests are getting 'placed' twice, and those people are spawning from a phantom incomplete town hall chest.

I've posted a workaround patch that should remove this issue, but doesn't solve the root cause -- where is the double creation of chests coming from. There's probably a tile entity being created somewhere that's got to go.
